.gitignore, README.rst, mache/__init__.py, mache/cime_machine_config/config_compilers.xml, mache/cime_machine_config/config_machines.xml, mache/machine_info.py, mache/machines/acme1.cfg, mache/machines/andes.cfg, mache/machines/anvil.cfg, mache/machines/badger.cfg, mache/machines/chrysalis.cfg, mache/machines/compy.cfg, mache/machines/cooley.cfg, mache/machines/cori-haswell.cfg, mache/machines/cori-knl.cfg, mache/machines/grizzly.cfg, setup.cfg, setup.py, spec-file.txt
`mache` is a package for providing configuration data relate to E3SM supported machines.
=> Initial draft of Machines for E3SM (mache) package

mache/machine_info.py
This merge adds a dictionary of environment variables to the return arguments for the function that polls `mache` for info about a compiler and MPI library.  These enviornment variables need to be set in order for certain compilers and MPI libraries to function as expected.
closes #6
=> Add environment variables to info for compiler/MPI 

conda/meta.yaml, mache/__init__.py, mache/machine_info.py, setup.cfg
This merge also updates to v1.1.1 for a bug-fix release
=> Make "web_portal" section if it doesn't exist

conda/meta.yaml, mache/__init__.py, mache/machines/badger.cfg, mache/machines/grizzly.cfg, setup.cfg
=> Fix Grizzly and Badger diagnostics paths

README.rst, mache/discover.py, mache/machines/grizzly.cfg
This reverts commit ee427955fcf84f97fc220159e7699a8153dc3260.
=> Put back `grizzly` as a machine

azure-pipelines.yml
This fix deletes cache files that are causing permission problems with `mamba`.
=> Add a fix to Azure

mache/cime_machine_config/config_machines.xml, mache/spack/chrysalis_gnu_openmpi.yaml, mache/spack/chrysalis_intel_openmpi.yaml, mache/spack/cori-haswell_gnu_mpt.csh, mache/spack/cori-haswell_gnu_mpt.sh, mache/spack/cori-haswell_gnu_mpt.yaml, mache/spack/cori-haswell_intel_mpt.csh, mache/spack/cori-haswell_intel_mpt.sh, mache/spack/cori-haswell_intel_mpt.yaml
Update Cori-Haswell and Chrysalis spack templates to match these changes.  No relevant updates to any other machines.
=> Update machines config to match E3SM

conda/meta.yaml, mache/version.py, setup.cfg
This is a bug-fix release to update modules on Cori-Haswell and Chrysalis
=> Update to v1.2.1

mache/spack/cori-haswell_gnu_mpt.csh, mache/spack/cori-haswell_gnu_mpt.sh, mache/spack/cori-haswell_intel_mpt.csh, mache/spack/cori-haswell_intel_mpt.sh
=> Remove git module on cori-haswell

conda/meta.yaml, mache/version.py, setup.cfg
=> Update to v1.3.0

conda/meta.yaml, mache/version.py, setup.cfg
This release just will include the bug fix in #38
=> Update to v1.3.2

mache/machines/acme1.cfg
Related to https://github.com/E3SM-Project/e3sm-unified/issues/103
=> Update acme1 `base_path`

mache/spack/anvil_gnu_mvapich.yaml, mache/spack/anvil_gnu_openmpi.yaml, mache/spack/anvil_intel_impi.yaml, mache/spack/anvil_intel_mvapich.yaml, mache/spack/anvil_intel_openmpi.yaml, mache/spack/badger_gnu_mvapich.yaml, mache/spack/badger_intel_impi.yaml, mache/spack/chrysalis_gnu_openmpi.yaml, mache/spack/chrysalis_intel_impi.yaml, mache/spack/chrysalis_intel_openmpi.yaml, mache/spack/compy_gnu_openmpi.yaml, mache/spack/compy_intel_impi.yaml, mache/spack/cori-haswell_gnu_mpt.yaml, mache/spack/cori-haswell_intel_mpt.yaml
This is new in 0.18.x and needed before 0.19.x
closes #55
=> Switch to `concretizer:unify:true`

conda/meta.yaml, mache/version.py
Oops!  This got missed in the update to v1.6.0
=> Update version to 1.6.0

mache/discover.py, mache/machine_info.py, mache/machines/pm-cpu.cfg, mache/spack/pm-cpu_gnu_mpich.csh, mache/spack/pm-cpu_gnu_mpich.sh, mache/spack/pm-cpu_gnu_mpich.yaml
This is the machine name for Perlmutter's CPU nodes at NERSC.
=> Add support for pm-cpu

mache/cime_machine_config/config_machines.xml, mache/spack/pm-cpu_gnu_mpich.csh, mache/spack/pm-cpu_gnu_mpich.sh, mache/spack/pm-cpu_gnu_mpich.yaml
Following https://github.com/E3SM-Project/E3SM/pull/5265
=> Update modules for pm-cpu

mache/cime_machine_config/config_machines.xml, mache/spack/pm-cpu_gnu_mpich.csh, mache/spack/pm-cpu_gnu_mpich.sh, mache/spack/pm-cpu_gnu_mpich.yaml
=> Update pm-cpu modules

mache/spack/anvil_gnu_mvapich.yaml
=> Add hdf5 to Anvil with Gnu and MVAPICH

conda/meta.yaml, mache/cime_machine_config/config_machines.xml, mache/spack/build_spack_env.template, mache/spack/chrysalis_gnu_openmpi.yaml, mache/spack/chrysalis_intel_impi.yaml, mache/spack/chrysalis_intel_openmpi.yaml, mache/version.py, setup.cfg
This merge also updates mache to v1.12.0rc1 and fixes a confusing "error" message that used to come up when testing to see if a spack environment already exists.
=> Fix Chrysalis OS in spack and update cime machine config file

.github/workflows/build_workflow.yml
Only lint files that have changed.
Run `mamba init` before trying to use `mamba activate`
=> Fix github action

.github/workflows/build_workflow.yml, conda/meta.yaml, setup.cfg
Add python 3.8 to GitHub Action
=> update to v1.13.0

conda/meta.yaml, mache/cime_machine_config/config_machines.xml, mache/spack/chicoma-cpu_gnu_mpich.csh, mache/spack/chicoma-cpu_gnu_mpich.sh, mache/spack/chicoma-cpu_gnu_mpich.yaml, mache/spack/pm-cpu_gnu_mpich.yaml, mache/version.py, setup.cfg
Various environment variables and modules have been updated to match E3SM master (commit 92db0e20e42cbd18e505ae2e0ac03569dd04a04a).
This merge also updates `config_machines.xml` to match E3SM master.
=> Update chicoma-cpu and pm-cpu spack

mache/spack/chicoma-cpu_gnu_mpich.csh, mache/spack/chicoma-cpu_gnu_mpich.sh
These are problematic for ESMF
=> Comment out OMP environment variables on Chicoma

mache/discover.py
Remove cori from the machines and remove some warnings that are not currently useful (because we don't support GPU machines yet)
=> Fix and simplify machine discovery

mache/discover.py
Use this to add expressions for compute nodes on Chrysalis, Blues and Compy.
closes #134
=> Switch to regular expression for discovery by host

mache/machines/andes.cfg
=> Update paths on Andes

mache/discover.py, mache/machines/polaris.cfg
This is used for E3SM input data
=> Add ALCF Polaris to machines

mache/spack/compy_gnu_openmpi.yaml
Was having trouble building these with Spack.
=> Add more system packages to Compy spack build

mache/cime_machine_config/config_machines.xml, mache/spack/chrysalis_intel_openmpi.yaml
This merge also updates the E3SM machine config file from https://github.com/E3SM-Project/E3SM/blob/rljacob/mach/new-chrys-soft/cime_config/machines/config_machines.xml which has not yet been merged into `master` but without which Chrysalis runs are hanging rather than canceling.
=> Update OpenMPI and other modules for Chrysalis

mache/__main__.py, mache/sync/__init__.py
I noticed a few format strings that could be updated to f-strings for better readability.
=> Update outdated format strings to f-strings

conda/meta.yaml, mache/version.py
This PR updates the version number for mache in three files: `conda/meta.yaml`, `version.py`, and `setup.cfg`.
Checklist
=> Update to 1.24.0

.github/pull_request_template.md
I updated the PR template to include various documentation-related checks on the checklist.
=> Update PR template to add documentation-related checks

mache/spack/chicoma-cpu_nvidia_mpich.csh, mache/spack/chicoma-cpu_nvidia_mpich.sh, mache/spack/chicoma-cpu_nvidia_mpich.yaml, mache/spack/pm-cpu_nvidia_mpich.sh, mache/spack/pm-cpu_nvidia_mpich.yaml
This PR adds the necessary `.yaml`, `.sh` and `.csh` files to add nvidia support for `chicoma-cpu` to mache. 
While creating these files, I noticed two small typos in `pm-cpu` files, so I included the fixes for those as well.
closes #182 
Checklist
=> Add nvidia support for `chicoma-cpu`

mache/spack/compy_gnu_openmpi.yaml, mache/spack/compy_intel_impi.yaml
Otherwise, spack will try to build it
Checklist
=> Add python to compy spack

mache/cime_machine_config/config_machines.xml, mache/spack/chrysalis_gnu_openmpi.yaml, mache/spack/chrysalis_intel_impi.yaml, mache/spack/chrysalis_intel_openmpi.yaml
For simplicity, use modules only, not prefixes
Checklist
=> Update netcdf-c and netcdf-fortran on chrysalis 

mache/spack/pm-cpu_nvidia_mpich.yaml, mache/spack/pm-gpu_nvidiagpu_mpich.yaml
=> Fix Perlmutter nvidia spack

mache/spack/frontier_amdclang_mpich.csh, mache/spack/frontier_amdclang_mpich.sh, mache/spack/frontier_amdclang_mpich.yaml, mache/spack/frontier_amdclanggpu_mpich.csh, mache/spack/frontier_amdclanggpu_mpich.sh, mache/spack/frontier_amdclanggpu_mpich.yaml
=> Add amdclang support on frontier

pyproject.toml
This merge also cleans up some unneeded wildcards in dir names.
=> Add `tests` to dirs excluded from package

.gitignore, mache/cime_machine_config/__init__.py, mache/io.py, mache/machines/__init__.py, spec-file.txt, utils/README.md, utils/update_cime_machine_config.py
=> Add a utility that shows updates to `config_machines.xml`

mache/cime_machine_config/config_machines.xml, mache/spack/frontier_crayamd-mphipcc_mpich.csh, mache/spack/frontier_crayamd-mphipcc_mpich.sh, mache/spack/frontier_crayamd-mphipcc_mpich.yaml, mache/spack/frontier_crayamd_mpich.csh, mache/spack/frontier_crayamd_mpich.sh, mache/spack/frontier_crayamd_mpich.yaml, mache/spack/frontier_craygnu-hipcc_mpich.csh, mache/spack/frontier_craygnu-hipcc_mpich.sh, mache/spack/frontier_craygnu-hipcc_mpich.yaml, mache/spack/frontier_craygnu-mphipcc_mpich.csh, mache/spack/frontier_craygnu-mphipcc_mpich.sh, mache/spack/frontier_craygnu-mphipcc_mpich.yaml, mache/spack/frontier_craygnu_mpich.csh, mache/spack/frontier_craygnu_mpich.sh, mache/spack/frontier_craygnu_mpich.yaml
=> Update `config_machines.xml` and frontier spack

docs/developers_guide/quick_start.md, mache/cime_machine_config/config_machines.xml, mache/discover.py, mache/machines/aurora.cfg, mache/spack/templates/aurora_oneapi-ifx_mpich.csh, mache/spack/templates/aurora_oneapi-ifx_mpich.sh, mache/spack/templates/aurora_oneapi-ifx_mpich.yaml
Support has been added for Aurora, including:
* a machine config file
* discovery of both login and compute nodes
* spack templates for `oneapi-ifx` and `mpich`
Checklist
closes #197
=> Add support for Aurora

docs/developers_guide/api.md, mache/spack/__init__.py, mache/spack/config_machines.py, mache/spack/list.py, utils/README.md, utils/extract_all_spack_from_config_machines.py
=> Add functions for creating spack shell scripts from `config_machines.xml`

mache/spack/templates/pm-cpu_gnu_mpich.csh, mache/spack/templates/pm-cpu_gnu_mpich.sh, mache/spack/templates/pm-cpu_gnu_mpich.yaml, mache/spack/templates/pm-cpu_intel_mpich.csh, mache/spack/templates/pm-cpu_intel_mpich.sh, mache/spack/templates/pm-cpu_intel_mpich.yaml, mache/spack/templates/pm-cpu_nvidia_mpich.csh, mache/spack/templates/pm-cpu_nvidia_mpich.sh, mache/spack/templates/pm-cpu_nvidia_mpich.yaml, mache/spack/templates/pm-gpu_gnugpu_mpich.csh, mache/spack/templates/pm-gpu_gnugpu_mpich.sh, mache/spack/templates/pm-gpu_gnugpu_mpich.yaml, mache/spack/templates/pm-gpu_nvidiagpu_mpich.csh, mache/spack/templates/pm-gpu_nvidiagpu_mpich.sh, mache/spack/templates/pm-gpu_nvidiagpu_mpich.yaml, mache/version.py
the `libfabric` module we were using has been removed during recent maintenance and needs to be updated.
Checklist
=> Update libfabric on pm-cpu and pm-gpu

mache/cime_machine_config/config_machines.xml
No spack changes appear to be needed.  We already removed the craygnu-hipcc compiler on frontier in #287.
=> Update config_machines.xml to E3SM commit f163f06
