- MANIFEST.in
- conda/meta.yaml
- conda/run_test.py
- mache/__init__.py
- mache/discover.py
- mache/machine_info.py
- mache/machines/acme1.cfg
- mache/machines/andes.cfg
- mache/machines/anvil.cfg
- mache/machines/badger.cfg
- mache/machines/chrysalis.cfg
- mache/machines/compy.cfg
- mache/machines/cooley.cfg
- mache/machines/cori-haswell.cfg
- mache/machines/cori-knl.cfg
- mache/machines/grizzly.cfg
- setup.cfg
This can be used to detect if a given machine is an E3SM supported machine before creating a `MachineInfo()` object.
This merge also fixes how package data is handled (wildcards do not seem to work).
A conda recipe has been added.
New config options have been added related to parallel computing.
>  Break out `discover_machine()` as separate function 

- mache/machine_info.py
- mache/machines/cori-haswell.cfg
- mache/machines/cori-knl.cfg
This merge switches the config options associated with Cori's two configurations (haswell and knl) to be called "configurations" rather than "partitions", to be consistent with their usage in Slrum.
closes #5
> Switch Cori from partitions to configurations

- conda/meta.yaml
- mache/__init__.py
- mache/machines/anvil.cfg
- mache/machines/chrysalis.cfg
- setup.cfg
We want diagnostics to go into `diagnostic_output` directory on the web portal.
Update `mache` to v1.1.2
> Fix LCRC web portal 

- conda/meta.yaml
- mache/__init__.py
- mache/machines/andes.cfg
- setup.cfg
The most recent E3SM-Unified versions have been installed in `cli115`, not `cli900`.
> Fix andes e3sm-unified path and group

- conda/meta.yaml
- mache/__init__.py
- mache/machine_info.py
- setup.cfg
Environment variables that include `$SHELL{}` were not being parsed correctly.
> Replace `$SHELL{}` with `$()` in environment variables

- mache/machines/chrysalis.cfg
For the purposes of any code running on Chrysalis, it looks like it has 128 CPUs per node because of hyperthreading.
> Upute chrysalis cores per node to 128

- mache/machines/chrysalis.cfg
We're having trouble with NCO compiled with Intel on this particular machine.  `ncremap` is producing strange results.
> Switch E3SM-Unified compiler on Chrysalis to Gnu

- mache/machines/cori-knl.cfg
This is because we have not had any luck getting Spack to build the E3SM-Unified packages on Cori-KNL.
> Remove compilers for E3SM-Unified on Cori-KNL

- mache/spack/anvil_intel_impi.yaml
- mache/spack/anvil_intel_mvapich.yaml
- mache/spack/anvil_intel_openmpi.yaml
- mache/spack/compy_intel_impi.yaml
This is necessary to get proper support for C++14.
> Add load gcc module before intel on Anvil and Compy

- mache/spack/badger_gnu_mvapich.yaml
- mache/spack/badger_intel_impi.yaml
The old cmake used by E3SM is too old for trilinos
> Update cmake on badger

- mache/spack/__init__.py
The new `yaml_template` argument can point to a yaml file from a different package that may have compiler or other package
versions that aren't the E3SM defaults.  This is useful if the E3SM compilers or other packages are too out-of-date to build certain libraries, as we are finding with Trilinos on some machines.
> Add arg for yaml template from outside mache

- mache/spack/__init__.py
This is useful if the default (`/tmp`) tends to run out of space.
> Add arg for specifying spack temp. directory

- conda/meta.yaml
- mache/spack/__init__.py
- mache/spack/chrysalis_intel_openmpi.yaml
- mache/spack/cori-knl_intel_impi.sh
- mache/spack/grizzly_gnu_mvapich.sh
- mache/spack/grizzly_intel_impi.sh
- mache/version.py
- setup.cfg
Although grizzly and cori-knl aren't supported under spack, this merge makes it possible to get compilers and module files in order to perform non-spack builds of libraries such as SCORPIO and ESMF.
This merge also fixes a typo in the yaml file for Chrysalis with Intel and OpenMPI.
The version of mache has been updated to 1.3.1 in anticipation of a bug-fix release.
> Add modules for grizzly and cori-knl

- mache/spack/compy_intel_impi.csh
- mache/spack/compy_intel_impi.sh
This merge brings in two missing paths in the Intel module on Compy that E3SM also explicitly adds.
> Add missing env variable for compy

- mache/permissions.py
This makes it easier to update permissions on spack branches and other shared directories (e.g. conda environments) across different packages.
> Add a module for updating permissions on directories

- mache/cime_machine_config/config_machines.xml
- mache/spack/chrysalis_gnu_openmpi.yaml
- mache/spack/chrysalis_intel_openmpi.yaml
This merge updates `config_machines.xml` from `E3SM/master`, which changes the version of OpenMPI on Chrysalis (among other changes unrelated to `mache`).
This merge also updates the Spack templates for Chrysalis to use the new OpenMPI and related modules.
Related E3SM PR:
https://github.com/E3SM-Project/E3SM/pull/4890
> Update Chrysalis Spack with new OpenMPI

- README.rst
- conda/meta.yaml
- mache/__main__.py
- mache/machines/acme1.cfg
- mache/machines/andes.cfg
- mache/machines/anvil.cfg
- mache/machines/badger.cfg
- mache/machines/chrysalis.cfg
- mache/machines/compy.cfg
- mache/machines/cooley.cfg
- mache/machines/cori-haswell.cfg
- mache/machines/cori-knl.cfg
- mache/machines/grizzly.cfg
- mache/sync/__init__.py
- mache/sync/diags.py
- setup.cfg
- spec-file.txt
This tool can be used to update diagnostics on any supported machine without a firewall with a command like:
```
mache sync diags from anvil -u <ac.user>
```
The LCRC username `<ac.user>` is needed on all machines except Anvil and Chrysalis.  For this to work, the user needs to have their public SSH key for non-LCRC supported machine registered to their LCRC account.  See the README for details.
There is an alternative procedure:
```
mache sync diags to badger -u <username>
```
for syncing diagnostics to a machine with a firewall (`badger` in this example).
> Add command-line tools for syncing diagnostics data

- mache/machine_info.py
- mache/machines/cori-haswell.cfg
- mache/machines/cori-knl.cfg
It should have been `constraint` in the first place because this is the term used in Slurm.
> Change `configuration` to `constraint` in Slurm

- mache/spack/__init__.py
- mache/spack/anvil_gnu_mvapich.yaml
- mache/spack/anvil_gnu_openmpi.yaml
- mache/spack/anvil_intel_impi.yaml
- mache/spack/anvil_intel_mvapich.yaml
- mache/spack/anvil_intel_openmpi.yaml
- mache/spack/badger_gnu_mvapich.yaml
- mache/spack/badger_intel_impi.yaml
- mache/spack/chrysalis_gnu_openmpi.yaml
- mache/spack/chrysalis_intel_impi.yaml
- mache/spack/chrysalis_intel_openmpi.yaml
- mache/spack/compy_intel_impi.yaml
- mache/spack/cori-haswell_gnu_mpt.csh
- mache/spack/cori-haswell_gnu_mpt.sh
- mache/spack/cori-haswell_gnu_mpt.yaml
- mache/spack/cori-haswell_intel_mpt.yaml
This is needed because MPAS standalone expects Netlib-LAPACK, which conflicts with other LAPACK installations in a given spack environment.
> Make LAPACK from E3SM optional in Spack builds

- conda/meta.yaml
- mache/spack/chrysalis_gnu_openmpi.yaml
- mache/spack/chrysalis_intel_impi.yaml
- mache/spack/chrysalis_intel_openmpi.yaml
- mache/version.py
- setup.cfg
The OS on Chrysalis seems to have changed from Centos 8 to RHEL 8 in the latest maintenance (or at least Spack thinks so).
> Fix Chrysalis OS and update to mache v1.4.1

- mache/sync/diags.py
This is needed for atmosphere diags (obviously).
> Add back the `observations/Atm` dir. in diags sync

- mache/spack/compy_gnu_openmpi.csh
- mache/spack/compy_gnu_openmpi.sh
- mache/spack/compy_gnu_openmpi.yaml
This may be needed for `ncremap` to work properly on Compy for the next E3SM-Unified release.
> Add Gnu and OpenMPI to Compy spack support

- mache/machines/andes.cfg
- mache/machines/anvil.cfg
- mache/machines/chrysalis.cfg
- mache/machines/compy.cfg
- mache/machines/cori-haswell.cfg
- mache/machines/cori-knl.cfg
Update Cori `base_url` to use `/cfs/` rather than `/project/`. Resolves #52.
> Update Cori base_url

- mache/spack/anvil_intel_impi.yaml
- mache/spack/chrysalis_intel_impi.yaml
- mache/spack/compy_intel_impi.yaml
This is needed so intel-mpi can find libfabric when linking system libraries built with it into spack libraries.  This has been seen when linking netcdf-c into nco, for example.
> Add `extra_rpaths` to all intel-mpi environments

- mache/spack/pm-cpu_gnu_mpich.csh
- mache/spack/pm-cpu_gnu_mpich.sh
- mache/spack/pm-cpu_gnu_mpich.yaml
This is its own module, and somehow I seem to have missed that.
> Fix libfabric on pm-cpu

- mache/cime_machine_config/config_machines.xml
- mache/machines/cori-haswell.cfg
- mache/machines/cori-knl.cfg
- mache/machines/pm-cpu.cfg
- mache/spack/__init__.py
There is now a config option to set if a machine uses cray compilers.  This is much easier to maintain than a hidden list of cray machines.
This merge also updates the machine config file to match E3SM master.
> Fix handling of cray compilers

- mache/machines/acme1.cfg
- mache/sync/diags.py
This merge also adds support for a custom config file to `mache sync diags`, a feature that could be used to provide a non-default diagnostics directory and/or group for testing.
closes #66
> Fix diagnostics directory on acme1

- mache/sync/diags.py
This should prevent redundant directories `diagnostics/diagnostics` and `diagnostics/diagnostics_private`.
> Fix source diagnostics dir

- mache/spack/pm-cpu_gnu_mpich.yaml
Since we rebased spack onto its 0.19.0 tag and updated modules in #71, we have run into some troubles building on Perlmutter-CPU.  The difficulties seem to be resolved if:
- we load more modules for `gcc`
- we include the pre-build libxml2 (which is otherwise complaining about not finding a `cray-xpmem` pkgconfig file)
- we do *not* load modules for netcdf-c and netcdf-fortran (and pnetcdf for good measure) because the path determined from the module includes all available compilers, not just gnu.
> Fix pm-cpu yaml

- mache/spack/anvil_intel_impi.yaml
- mache/spack/anvil_intel_openmpi.yaml
We need to explicitly load intel compiler modules and not provide prefixes to intel compilers, mkl, or mpi libraries.
> Fix anvil yaml files following recent spack update

- conda/build.sh
- conda/meta.yaml
- conda/post-link.sh
- mache/discover.py
- mache/machine_info.py
If the machine name cannot be discovered at runtime from the host name or an environment variable, get it from a file created at install time.
closes #83
> Get machine name from file

- conda/meta.yaml
- mache/machine_info.py
- mache/spack/__init__.py
- setup.cfg
- spec-file.txt
For python 3.8, this requires using teh importlib_resources backport
> Replace deprecated importlib.resources calls

- mache/spack/chicoma-cpu_gnu_mpich.yaml
This is needed for building PETSc and building python in spack itself seems to take an inordinate amount of time and requires the mirror capability from #96.
> Add python to chicoma spack template

- mache/spack/__init__.py
- mache/spack/build_spack_env.template
This is needed for some packages on Chicoma, which blocks ftp downloads.
> Add support for a local spack mirror

- mache/machine_info.py
- mache/spack/__init__.py
The python version was not being constrained correctly, leading to using the python > 3.8 imports for python 3.8
> Fix importlib.resources constraints

- mache/spack/__init__.py
We want to be able to build spack environments for external machines that aren't supported by `mache` or E3SM.  This merge allows a config file to be passed to `make_spack_env()` and `get_spack_script()` for an external machine.  There is already support for passing a template yaml file for defining the spack environment.
I have tested this on my personal laptop `morpheus` and was able to create a spack environment (using compass) for it and use it to build standalone MPAS-Ocean.
> Build spack environments for external machines

- mache/cime_machine_config/config_machines.xml
- mache/spack/pm-cpu_gnu_mpich.csh
- mache/spack/pm-cpu_gnu_mpich.sh
- mache/spack/pm-cpu_intel_mpich.csh
- mache/spack/pm-cpu_intel_mpich.sh
- mache/spack/pm-cpu_intel_mpich.yaml
This merge updates `config_machines.xml` to match E3SM/master, now at E3SM commit fed770a9dd
It also updates pm-cpu gnu modules and environment variables to match E3SM.
Finally, it adds support for Intel compilers on pm-cpu.
> Add intel to pm-cpu

- mache/spack/chicoma-cpu_gnu_mpich.yaml
Spack isn't able to download these.
> Add more system libs to chicoma-cpu

- mache/spack/chicoma-cpu_gnu_mpich.yaml
Chicoma's firewall doesn't allow us to download the code for this one.
> Add more system packages to chicoma-cpu spack template

- mache/spack/pm-cpu_gnu_mpich.yaml
- mache/spack/pm-cpu_intel_mpich.yaml
It doesn't seem to be possible (or necessary) to build python on Perlmutter form spack.
> Use system python on pm-cpu

- mache/spack/chicoma-cpu_gnu_mpich.yaml
- mache/spack/pm-cpu_gnu_mpich.csh
- mache/spack/pm-cpu_gnu_mpich.sh
- mache/spack/pm-cpu_gnu_mpich.yaml
- mache/spack/pm-cpu_intel_mpich.csh
- mache/spack/pm-cpu_intel_mpich.sh
- mache/spack/pm-cpu_intel_mpich.yaml
This merge brings in a variety of fixes to spack builds on Perlmutter and Chicoma, including:
* making sure the `NERSC_HOST` variable is defined on PM
* fixing the specification for netcdf-c
* switching from `mpich` to `cray-mpich`
* Adding `netcdf-c`, `netcdf-fortran` and `hdf5` without MPI on PM
* Commenting out some OMP environment variables on PM that seem to cause issues with ESMF
> Perlmutter and Chicoma fixes

- MANIFEST.in
- mache/machines/anvil.cfg
- mache/machines/chicoma-cpu.cfg
- mache/machines/chrysalis.cfg
- mache/machines/compy.cfg
- mache/machines/pm-cpu.cfg
- mache/spack/__init__.py
- mache/spack/pm-cpu_gnu_mpich.yaml
- mache/spack/pm-cpu_intel_mpich.yaml
This merge includes the following fixes:
* Add `use_e3sm_hdf5_netcdf` config options to the `e3sm_unified` section of machine config files
* In E3SM-U, don't use E3SM HDF5, NetCDF or PNetCDF except for Cray machines
* Build with gnu on anvil and compy
* Add "system" rather than "e3sm" hdf5, netcdf, pnetcdf.  For E3SM-Unified, it doesn't seem to be possible to use the same HDF5 and NetCDF as E3SM because ESMF needs to use the non-parallel version.  This also means that we can't load the parallel modules at runtime (because ESMF will use them instead and will fail).
* Add missing csh files in mache.spack to the manifest
> Various fixes needed for E3SM-Unified

- mache/spack/pm-cpu_gnu_mpich.yaml
- mache/spack/pm-cpu_intel_mpich.yaml
The version without MPI support should not be in the e3sm_hdf5_netcdf section.
> Remove incorrect netcdf-fortran spec on pm-cpu

- mache/machines/compy.cfg
We are seeing errors with `ESMF_RegridWeightGen` on Compy when testing with the same files that work fine on other machines.
> Switch E3SM-Unified to intel and intel-mpi on Compy

- mache/machines/compy.cfg
This reverts commit 58452e0af0e00eefe5f18adfe72543d39f6d86b7.
> Switch E3SM-Unified back to gnu on Compy

- mache/cime_machine_config/config_machines.xml
- mache/machines/pm-gpu.cfg
- mache/spack/pm-cpu_gnu_mpich.csh
- mache/spack/pm-cpu_gnu_mpich.sh
- mache/spack/pm-cpu_gnu_mpich.yaml
- mache/spack/pm-cpu_intel_mpich.csh
- mache/spack/pm-cpu_intel_mpich.sh
- mache/spack/pm-cpu_intel_mpich.yaml
- mache/spack/pm-cpu_nvidia_mpich.csh
- mache/spack/pm-cpu_nvidia_mpich.sh
- mache/spack/pm-cpu_nvidia_mpich.yaml
- mache/spack/pm-gpu_gnu_mpich.csh
- mache/spack/pm-gpu_gnu_mpich.sh
- mache/spack/pm-gpu_gnu_mpich.yaml
- mache/spack/pm-gpu_gnugpu_mpich.csh
- mache/spack/pm-gpu_gnugpu_mpich.sh
- mache/spack/pm-gpu_gnugpu_mpich.yaml
- mache/spack/pm-gpu_nvidia_mpich.csh
- mache/spack/pm-gpu_nvidia_mpich.sh
- mache/spack/pm-gpu_nvidia_mpich.yaml
- mache/spack/pm-gpu_nvidiagpu_mpich.csh
- mache/spack/pm-gpu_nvidiagpu_mpich.sh
- mache/spack/pm-gpu_nvidiagpu_mpich.yaml
This merge updates the `config_machines.xml` file frm E3SM to commit 7f7920b
It also updates `pm-cpu` spack support:
* Updates `gnu` builds
* Adds `intel`
* Adds `nvidia`
This merge also adds `pm-gpu` support:
* Adds a machine config file that is mostly a copy of `pm-cpu`
* Adds `gnu`, `gnugpu`, `nvidia`, and `nvidiagpu` compilers to spack support
> Many updates to supported Perlmutter compilers

- mache/spack/pm-cpu_intel_mpich.csh
- mache/spack/pm-cpu_intel_mpich.sh
- mache/spack/pm-cpu_intel_mpich.yaml
It appears that we do need to explicitly load `libfabric`, even though doing so produces a warning.
> Fix intel on Perlmutter

- mache/machines/frontier.cfg
- mache/spack/frontier_gnu_mpich.yaml
This slipped through the cracks in #143
> Fix netcdf-fortran spack spec for frontier with gnu

- mache/spack/compy_intel_impi.yaml
These are needed because they are time consuming or simply not possible to build with spack.
> Add more system packages to Compy's spack template

- .github/workflows/build_workflow.yml
The test mache action will now run with Python 3.12 in addition to Python 3.8-3.11. Will test this behavior with the creation of this PR and update with the results in a comment.
> Update GitHub actions to additionally run Python 3.12

- .github/workflows/build_workflow.yml
In this PR, I updated the build workflow to use miniforge instead of mambaforge. I also made a small change to the pre-commit action that references the README - it was using the old file extension `.rst` which we just changed to `.md` in a previous PR.
The testing for this PR will start once the PR is created (as it changes actions that occur at PR-creation time). I will update the testing progress in the comments.
Checklist
> Switch all mamba actions to miniforge/conda

- mache/machines/frontier.cfg
- mache/machines/pm-gpu.cfg
This merge also fixes the incorrect `cores_per_node` value for Perlmutter-GPU.
Checklist
> Add `gpus_per_node` for machines with GPUs

- .github/workflows/build_workflow.yml
- .pre-commit-config.yaml
The pre-commit configuration and CI workflow both referred to the `setup.cfg` file which was deleted in the last PR. I've changed them to point to the `pyproject.toml` and `.flake8` file where necessary.
Checklist
> Update CI and pre-commit for new setup config files

- MANIFEST.in
- conda/meta.yaml
- pyproject.toml
- spec-file.txt
A previously added setuptools option, `setuptools-scm`, was set in #175 during the transition from `setup.cfg` to `pyproject.toml`, and this option ended up not working on the conda-forge feedstock. This PR removes that option and replaces it again with the `MANIFEST.in` file.
Checklist
> Fix setuptools on conda-forge feedstock

- mache/spack/chrysalis_gnu_openmpi.csh
- mache/spack/chrysalis_gnu_openmpi.sh
They are causing very bad slowdown in the Polaris pr test suite.
Checklist
> Omit OMP* environment variables with gnu on chrysalis

- .pre-commit-config.yaml
- pyproject.toml
- spec-file.txt
I'm updating the linting procedure to include `flynt`, which is a package that automatically searches for and replaces older-style format strings with f-strings (in most cases). This is a change we made a while ago in polaris (https://github.com/E3SM-Project/polaris/pull/74).
Checklist
> Add flynt package to linter

- pyproject.toml
This was accidentally included in the `pyproject.toml` file when it was created.
> Remove reference to e3sm-diags

- .github/workflows/build_workflow.yml
- conda/meta.yaml
- mache/machine_info.py
- mache/spack/__init__.py
- pyproject.toml
- spec-file.txt
I updated a few places where python 3.8 was referenced or used, and either removed them or changed them to 3.9. During this process, I also had to update some file formatting to comply with the linter. 
Checklist
> Drop python 3.8 from supported versions

- conda/meta.yaml
- mache/spack/pm-gpu_gnugpu_mpich.yaml
- mache/spack/pm-gpu_nvidiagpu_mpich.yaml
- mache/version.py
This is needed for Trilinos and Albany builds that include `cuda`.
Checklist
> Add `cuda` to `pm-gpu` yaml files for `spack` builds

- .github/workflows/build_workflow.yml
- .github/workflows/docs_workflow.yml
In this PR I made a few tweaks to the behavior of the CI workflows. These changes are:
1. `cancel_others` is now set to false by default, which should make it easier to decipher if a bug is isolated to a specific version of python via CI
2. The `defaults` channel has been removed as we can now exclusively use `conda-forge`
3. The timeout for the `pre-commit` job has been upped to 5 minutes
> Tweak CI workflow behavior

- .github/workflows/build_workflow.yml
- .github/workflows/docs_workflow.yml
- conda/build.sh
- docs/developers_guide/quick_start.md
In this PR I added a few flags to the `python -m pip install [-e] .` command. The flags are:
* `-vv` indicates very verbose output. This flag is used during the CI runs to help with debugging.
* `--no-deps` indicates that pip should not install runtime dependencies from PyPi.
* `--no-build-isolation` indicates that pip should not install build time dependencies from PyPi.
Checklist
> Add additional flags to `pip install` command

- mache/machines/anvil.cfg
- mache/machines/chicoma-cpu.cfg
- mache/machines/chrysalis.cfg
- mache/machines/compy.cfg
- mache/machines/frontier.cfg
- mache/machines/pm-cpu.cfg
- mache/machines/pm-gpu.cfg
- mache/spack/__init__.py
- mache/spack/chicoma-cpu_gnu_mpich.yaml
- mache/spack/chicoma-cpu_nvidia_mpich.yaml
- mache/spack/frontier_crayclang_mpich.yaml
- mache/spack/frontier_crayclanggpu_mpich.yaml
- mache/spack/frontier_gnu_mpich.yaml
- mache/spack/frontier_gnugpu_mpich.yaml
- mache/spack/pm-cpu_gnu_mpich.yaml
- mache/spack/pm-cpu_intel_mpich.yaml
- mache/spack/pm-cpu_nvidia_mpich.yaml
- mache/spack/pm-gpu_gnugpu_mpich.yaml
- mache/spack/pm-gpu_nvidiagpu_mpich.yaml
This PR removes the deprecated `include_system_hdf5_netcdf` and `system_hdf5_netcdf` from Spack files and machine config files.
Checklist
> Remove `[include_]system_hdf5_netcdf`

- .pre-commit-config.yaml
This PR switches the recently added pre-commit `autoupdate_schedule` CI from monthly to weekly, so that we can observe the behavior sooner for testing. This will likely be switched back to monthly after we confirm that it works as expected.
> Switch pre-commit `autoupdate_schedule` to `weekly`

- conda/meta.yaml
- mache/version.py
This is useful for testing, particularly with spack, even before we are ready to actually make the release.
> Update to 1.26.0

- docs/conf.py
- pyproject.toml
- spec-file.txt
This merge removes `myst-to-rst` (which is not being maintained) and constrain sphinx to newer versions (>= 8.0.0).
It also includes some cleanup of the config script for the docs, including removing unused imports and removing an unneeded path to the read-the-docs theme files.
> Various fixes to the docs

- mache/spack/chicoma-cpu_gnu_mpich.csh
- mache/spack/chicoma-cpu_gnu_mpich.sh
- mache/spack/chicoma-cpu_gnu_mpich.yaml
- mache/spack/chicoma-cpu_nvidia_mpich.csh
- mache/spack/chicoma-cpu_nvidia_mpich.sh
- mache/spack/chicoma-cpu_nvidia_mpich.yaml
This PR updates `chicoma-cpu` to match the changes made in https://github.com/E3SM-Ocean-Discussion/E3SM/pull/112.
Checklist
> Update `chicoma-cpu` modules

- mache/cime_machine_config/config_machines.xml
- mache/spack/pm-cpu_gnu_mpich.csh
- mache/spack/pm-cpu_gnu_mpich.sh
- mache/spack/pm-cpu_gnu_mpich.yaml
- mache/spack/pm-cpu_intel_mpich.csh
- mache/spack/pm-cpu_intel_mpich.sh
- mache/spack/pm-cpu_intel_mpich.yaml
- mache/spack/pm-cpu_nvidia_mpich.csh
- mache/spack/pm-cpu_nvidia_mpich.sh
- mache/spack/pm-cpu_nvidia_mpich.yaml
- mache/spack/pm-gpu_gnugpu_mpich.csh
- mache/spack/pm-gpu_gnugpu_mpich.sh
- mache/spack/pm-gpu_gnugpu_mpich.yaml
- mache/spack/pm-gpu_nvidiagpu_mpich.csh
- mache/spack/pm-gpu_nvidiagpu_mpich.sh
- mache/spack/pm-gpu_nvidiagpu_mpich.yaml
> Update Perlmutter CPU and GPU

- .github/workflows/build_workflow.yml
- pyproject.toml
This PR adds python 3.13 to the list of supported python versions for mache in the `pyproject.toml` file as well as an additional CI test to run mache in python 3.13. No additional changes to the code were needed for this update.
Checklist
> Add support for python 3.13

- mache/spack/pm-cpu_intel_mpich.yaml
These filepaths changed, causing errors when building an intel environment on pm-cpu. This PR fixes them.
Checklist
> Fix intel module filepaths on pm-cpu

- .github/workflows/build_workflow.yml
- .github/workflows/pre_commit_update_workflow.yml
This adds a GitHub actions workflow that will run the `pre-commit autoupdate` command to update pre-commit and its dependencies. The workflow is set to run weekly on Wednesdays.
Checklist
> Add pre-commit autoupdate workflow

- .github/workflows/pre_commit_update_workflow.yml
This PR makes a few tweaks to the new pre-commit CI workflow. This workflow now skips the push and PR-creating steps when no changes are present (i.e., when pre-commit is already up-to-date). Also, PRs created via this action will automatically be assigned reviewers and a `ci` label.
Checklist
> Tweak pre-commit autoupdate CI workflow

- .github/workflows/build_workflow.yml
- .github/workflows/docs_workflow.yml
- .github/workflows/pre_commit_update_workflow.yml
This PR updates the build workflow to use separate directories for each python version for conda caching. Issues with this seem to have been crashing CI runs lately.
I also fixed a bug in the docs workflow, where it was referring to a nonexistent python version matrix (likely a remnant of copying from the build workflow). Instead, I set this to be an environment variable called `PYTHON_VERSION` which will allow us to more easily specify and update the python version we use for the documentation without having to change it in a couple different places. I also copied this convention into the pre-commit update workflow for consistency.
Checklist
> Use separate conda cache directories in CI

- mache/machines/anvil.cfg
- mache/machines/chicoma-cpu.cfg
- mache/machines/chrysalis.cfg
- mache/machines/compy.cfg
- mache/machines/frontier.cfg
- mache/machines/pm-cpu.cfg
- mache/machines/pm-gpu.cfg
This was removed rather than renamed in #198
Checklist
> Add back `use_e3sm_hdf5_netcdf` config option

- docs/developers_guide/quick_start.md
- mache/sync/diags.py
This is needed because it is no possible to log into LCRC machines from Frontier or Andes (since the introduction of Duo Mobile).
Checklist
> Allow diags to be synced from LCRC to remote

- mache/spack/anvil_gnu_mvapich.yaml
- mache/spack/anvil_gnu_openmpi.yaml
- mache/spack/anvil_intel_impi.yaml
- mache/spack/anvil_intel_mvapich.yaml
- mache/spack/anvil_intel_openmpi.yaml
- mache/spack/chicoma-cpu_gnu_mpich.yaml
- mache/spack/chicoma-cpu_nvidia_mpich.yaml
- mache/spack/chrysalis_gnu_openmpi.yaml
- mache/spack/chrysalis_intel_impi.yaml
- mache/spack/chrysalis_intel_openmpi.yaml
- mache/spack/compy_gnu_openmpi.yaml
- mache/spack/compy_intel_impi.yaml
- mache/spack/frontier_crayclang_mpich.yaml
- mache/spack/frontier_crayclanggpu_mpich.yaml
- mache/spack/frontier_gnu_mpich.yaml
- mache/spack/frontier_gnugpu_mpich.yaml
- mache/spack/pm-cpu_gnu_mpich.yaml
- mache/spack/pm-cpu_intel_mpich.yaml
- mache/spack/pm-cpu_nvidia_mpich.yaml
- mache/spack/pm-gpu_gnugpu_mpich.yaml
- mache/spack/pm-gpu_nvidiagpu_mpich.yaml
We are seeing:
```
==> Warning: The config:install_missing_compilers option has been deprecated in Spack v0.23, and is currently ignored. It will be removed from config in Spack v0.25.
```
This merge removes the deprecated config option.
Checklist
> Remove deprecated `install_missing_compilers` spack config

- .github/workflows/build_workflow.yml
In this PR, I've removed the conda caching job from the build workflow. This will hopefully fix the random CI crashing errors we're seeing across many repos right now. 
Checklist
> Remove conda caching in CI

- .github/workflows/docs_workflow.yml
This is a follow-up to #225 which also removes the conda caching job in the docs workflow.
Checklist
> Remove conda caching in the docs workflow

- mache/spack/anvil_gnu_mvapich.yaml
- mache/spack/anvil_gnu_openmpi.yaml
- mache/spack/anvil_intel_impi.yaml
- mache/spack/anvil_intel_mvapich.yaml
- mache/spack/anvil_intel_openmpi.yaml
- mache/spack/chicoma-cpu_gnu_mpich.yaml
- mache/spack/chrysalis_gnu_openmpi.yaml
- mache/spack/compy_gnu_openmpi.yaml
- mache/spack/frontier_gnu_mpich.yaml
- mache/spack/frontier_gnugpu_mpich.yaml
- mache/spack/pm-cpu_gnu_mpich.yaml
- mache/spack/pm-gpu_gnugpu_mpich.yaml
This is needed in the latest spack release because of changes made to how the `gcc` package detects the path to the compilers themselves.
This PR also changes Anvil spack to point its correct zlib (and not the version on Chrysalis).
Checklist
> Add `extra_attributes` to all external gcc spack packages

- mache/cime_machine_config/config_machines.xml
- mache/spack/chicoma-cpu_gnu_mpich.csh
- mache/spack/chicoma-cpu_gnu_mpich.sh
- mache/spack/frontier_amdclang_mpich.csh
- mache/spack/frontier_amdclang_mpich.sh
- mache/spack/frontier_amdclang_mpich.yaml
- mache/spack/frontier_amdclanggpu_mpich.csh
- mache/spack/frontier_amdclanggpu_mpich.sh
- mache/spack/frontier_amdclanggpu_mpich.yaml
- mache/spack/frontier_crayclang_mpich.csh
- mache/spack/frontier_crayclang_mpich.sh
- mache/spack/frontier_crayclang_mpich.yaml
- mache/spack/frontier_crayclanggpu_mpich.csh
- mache/spack/frontier_crayclanggpu_mpich.sh
- mache/spack/frontier_crayclanggpu_mpich.yaml
- mache/spack/frontier_gnu_mpich.csh
- mache/spack/frontier_gnu_mpich.sh
- mache/spack/frontier_gnu_mpich.yaml
- mache/spack/frontier_gnugpu_mpich.csh
- mache/spack/frontier_gnugpu_mpich.sh
- mache/spack/frontier_gnugpu_mpich.yaml
- mache/spack/pm-cpu_gnu_mpich.csh
- mache/spack/pm-cpu_gnu_mpich.sh
- mache/spack/pm-cpu_intel_mpich.csh
- mache/spack/pm-cpu_intel_mpich.sh
- mache/spack/pm-cpu_nvidia_mpich.csh
- mache/spack/pm-cpu_nvidia_mpich.sh
This merge makes updates to Frontier, Perlmutter and Chicoma based on changes to `config_machines.xml` since it was last updated (#206).
Checklist
> Update CIME config machines

- conda/meta.yaml
- mache/version.py
This differs from 1.28.0 only in pointing to a different spack branch
> Update to v1.29.0

- mache/machines/chicoma-cpu.cfg
I am having trouble with installing mpi4py with system compilers on LANL's Chicoma machine and it's just not worth the trouble to fix this.  Instead, I think we can provide E3SM-Unified without system compiler and MPI support, like we do in Andes and ALCF Polaris.
Checklist
> Drop spack build in E3SM-Unified on Chicoma

- conda/meta.yaml
- pyproject.toml
This pull request includes small changes to the dependencies in the `conda/meta.yaml` and `pyproject.toml` files. The changes add the `termcolor` package to the list of dependencies in both files.
Dependency updates:
* [`conda/meta.yaml`](diffhunk://#diff-e4db5852c039b631ee11f2e6f3b000f53e0774918ff1ba8f983f428f72b4fe4cR28): Added `termcolor` to the `requirements` section.
* [`pyproject.toml`](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R30): Added `termcolor` to the `dependencies` section.
> Add `termcolor` dependency

- .github/pull_request_template.md
- docs/conf.py
- docs/developers_guide/api.md
- docs/developers_guide/contributing.md
- docs/developers_guide/quick_start.md
- docs/developers_guide/spack.md
- docs/index.md
- docs/users_guide/quick_start.md
- docs/users_guide/spack/build.md
- mache/machine_info.py
- mache/spack/__init__.py
This PR reorganizes the `mache.spack` package by breaking the functions which are currently in `mache.spack.__init__` to three separate files, `mache.spack.env`, `mache.spack.script`, and `mache.spack.shared`. This will allow for better modularization for changes we're expecting to make to the spack template creation process.
Checklist
> Reorganize `mache.spack` for better modularization

- mache/spack/templates/compy_intel_impi.yaml
This avoids trying to build it with spack.
Checklist
> Use system module for cmake on Compy

- mache/spack/env.py
Spack will fail with a slightly complicated error message if it can not write to the `tmpdir` passed to the `mache.spack.make_spack_env` function (i.e. if the `tmpdir` does not already exist).
> Make tmpdir if it does not exist

- .github/workflows/pre_commit_update_workflow.yml
This allows us to install `gh` ourselves and avoid a buggy version (2.76.0)
Checklist
> Switch pre-commit update workflow to use conda

- .github/workflows/pre_commit_update_workflow.yml
This PR just implements the two-token solution @xylar discovered that fixes the permissions errors we're seeing with the pre-commit update job.
Checklist
> Implement two-token method in `pre-commit` CI

- .github/workflows/pre_commit_update_workflow.yml
This merge makes a minor update to the pre-commit update workflow configuration. The change removes the automatic assignment of reviewers when creating pull requests for pre-commit dependency updates.
> Fix pre-commit update action

- mache/spack/templates/chicoma-cpu_gnu_mpich.csh
- mache/spack/templates/chicoma-cpu_gnu_mpich.sh
- mache/spack/templates/chicoma-cpu_gnu_mpich.yaml
- mache/spack/templates/chicoma-cpu_nvidia_mpich.csh
- mache/spack/templates/chicoma-cpu_nvidia_mpich.sh
- mache/spack/templates/chicoma-cpu_nvidia_mpich.yaml
Hey @xylar! I know `chicoma` isn't really a `mache` supported machine anymore, since the recharge model changes. But, Trevor has an allocation and needed a custom deployment of compass environments. 
As of April 28th, 2025 LANL no longer supports the proxy settings, and actually blocks traffic through them. So I've removed those from shell scripts. 
As of [#7230](https://github.com/E3SM-Project/E3SM/pull/7230) Chicoma has been updated to use cmake `3.29.6`, which is also update here.
> Update configs for Chicoma
